apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cpp-main-hpa
  namespace: cpp-application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpp-main-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
